# Generated by Django 3.0 on 2022-01-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20220130_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=127),
            preserve_default=False,
        ),
    ]
