# Generated by Django 3.0 on 2022-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='Joe', max_length=255),
            preserve_default=False,
        ),
    ]
